language: node_js
node_js:
  - '14'
  - '12'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

env:
  - NODE_ENV=development
